### ISSUE TITLE
pumpify messes with browser duplex

### ISSUE THREAD

**Issue by finnp** [mafintosh/pumpify#1]
Hey,

I just figured that when I require `pumpify` in my code, the Duplex stream is not working anymore.

So if I do
```
var pumpify = require('pumpify') // without this line it works
var Duplex = require('stream').Duplex
new Duplex()
```

and run this in the browser or in testling with `browserify temp.js | testling`, I get
```
not ok 1 Error: TypeError: 'undefined' is not a function (evaluating 'this.once('end', onend)') on line 7182
```

The line that throws the error looks like this: ` this.once('end', onend);`.

Best,
Finn

**Comment by mafintosh** [comment]
This is because of a race condition inregards to circular dependencies and the `stream` module in old versions of browserify. Should be fixed in later versions.
