### ISSUE TITLE
Problem with `readable-stream@3` and async iteration

### ISSUE THREAD

**Issue by targos** [mafintosh/pumpify#11]
Note: to reproduce, `duplexify` must be updated to version 4 (to get `readable-stream@3`. I published `@targos/pumpify` with upgraded dependencies (https://github.com/targos/pumpify/commit/396b36037b1014370c68186d5c9716fca3928226).

If async iteration is used on a pumpify stream, it works correctly as long as the loop is not ended prematurely (by throwing an error or `break`ing).
According to [readable-stream](https://github.com/nodejs/readable-stream/blob/4ba93f84cf8812ca2af793c7304a5c16de72088a/lib/internal/streams/async_iterator.js#L126-L138), the `destroy` method must support a callback as second argument. However, it is described as private API that shouldn't be handle by userland.

See https://github.com/targos/bug-stream-async-iteration/blob/master/test.js for an example of the issue.

/cc @mcollina @mafintosh

**Comment by mafintosh** [comment]
Should be fixed in 2.0.0 - Let me know if not
