### ISSUE TITLE
Mixing object mode with "normal" mode.

### ISSUE THREAD

**Issue by arb** [mafintosh/pumpify#3]
If I have a mix of streams that are in object mode and streams that are in "normal" buffer mode, what will the impact be between using `pumpify.obj` and regular `pumpify`?

**Comment by mafintosh** [comment]
You should use `.obj` if the stream returned by pumpify should be an object stream. The pipeline itself can be a mix of both

**Comment by arb** [comment]
Got it. Thank you!

**Comment by mk-pmb** [comment]
The last stream in my pipeline eats Buffers and makes Objects from them. What should I do? With .obj I get

> Invalid non-string/buffer chunk

but without it I get

> The "chunk" argument must be one of type string, Buffer, or Uint8Array. Received type object
