### ISSUE TITLE
Write after end

### ISSUE THREAD

**Issue by phated** [mafintosh/pumpify#6]
I'm not sure if I'm using `pumpify` wrong or if I stumbled upon a bug.

This example causes a "write after end" error:

```js
var pumpify = require('pumpify');
var miss = require('mississippi');

function double() {
  return miss.through.obj(function(num, _, cb) {
    cb(null, num * 2);
  });
}

function log(results) {
  console.log(results);
}

miss.pipe([
  miss.from.obj([1,2,3]),
  pumpify.obj(miss.from.obj([100,200,300]), double()),
  miss.concat({ encoding: 'object' }, log)
], log);
```

I have readable stream as the first argument to pumpify (which is likely causing this), but I thought that a duplex stream could be used in this fashion.  Let me know if you need any other information.  Thanks!

**Comment by mafintosh** [comment]
You have a bug

``` js
  pumpify.obj(miss.from.obj([100,200,300]), double()),
```

miss.from is a readable stream and not a writable one

**Comment by phated** [comment]
In my actual usage, I have a readable stream that adds data to the stream if inserted into the middle of a pipeline. We've traditionally done this with a separate through stream that we write to, but I was trying to clean that up with pumpify.

**Comment by mafintosh** [comment]
You cannot write to a readable stream. That gives you that error you get.

**Comment by phated** [comment]
Yeah, the thing that is confusing me is duplex streams. When I attempt to pipe to a readable, it throws because the write method doesn't exist but the duplex stream doesn't behave that way. Is there a different type of stream I should be looking for?

**Comment by yoshuawuyts** [comment]
Duplex streams are a readable stream and writeable stream put together.
This means you can both read and write to these. Transform streams are a
special type of duplex stream where the data that is sent into the
writeable stream is transformed and then exposed through the readable
stream. In a pipeline as shown in your example it seems you're looking to
use transform streams.

Through2 (or the Mississippi equivalent) is the most common way to create
transform streams; perhaps that might be worth looking into. Cheers!

**Comment by phated** [comment]
@yoshuawuyts I've used `through2` extensively; however, it doesn't seem semantically proper to use a Transform stream at the head of a pipeline.  Or am I wrong?

**Comment by phated** [comment]
I've created https://github.com/armed/ordered-read-streams/issues/13 about by actual usage.  I think making it inherit from Duplex instead of Readable solves the issue.  Does that solution make sense?

**Comment by phated** [comment]
After digging into how vinyl-fs achieves this, it seems like the following works:
```js
var readable = from(["hello", "world"]);
var thru = through2.obj();
var stream = duplexify.obj(thru, merge(readable, thru));
```
I'm not completely sure how, but it seems to be working.
