### ISSUE TITLE
does pumpify not emit "end" when an error happens?

### ISSUE THREAD

**Issue by firemuzzy** [mafintosh/pumpify#7]
Given streams A, B, C are streams I have 
`const stream = pumpify.obj(A, B, C)`

if A emits `error` followed by an emit of `end`, the pumpified `stream` emits `error` but does not emit `end`. Is that the correct behavior? Does a pumpify pipeline close on an error only emitting an error event without emitting an end.  

Still trying to understand Node streams, but from what I got on normal Node streams an error does not stop the stream so there is also an end. I am writing some code that has to know when a pipeline finishes hence my confusion with `error` and `end`

Therefore to know if something finished successfully do I just listen to `end` and to know if something finished failing i listen to `error`.

**Comment by firemuzzy** [comment]
never mind, it was a problem with a ParallelTransfrom library I was using. It and pumpify do not play together well when the ParallelTransfrom stream is the last one in the pipeline.

**Comment by mafintosh** [comment]
Are you sure you are draining the last stream in the pipeline?
